test: Resolve build error as os_wrapper is removed and CMSIS is used directly
[ 84%] Building C object test/suites/ps/CMakeFiles/tfm_test_suite_ps_ns.dir/non_secure/ns_test_helpers.o.
/data_sda/Workspace/mbed-os-tf-m-regression-tests/mbed-os/platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_1/TARGET_IGNORE/tf-m-tests/test/suites/ps/non_secure/ns_test_helpers.c:11:10: fatal error: cmsis_os2.h: No such file or directory.
11 | #include "cmsis_os2.h".
compilation terminated..
test/suites/ps/CMakeFiles/tfm_test_suite_ps_ns.dir/build.make:81: recipe for target 'test/suites/ps/CMakeFiles/tfm_test_suite_ps_ns.dir/non_secure/ns_test_helpers.o' failed.
make[2]: *** [test/suites/ps/CMakeFiles/tfm_test_suite_ps_ns.dir/non_secure/ns_test_helpers.o] Error 1.
CMakeFiles/Makefile2:3376: recipe for target 'test/suites/ps/CMakeFiles/tfm_test_suite_ps_ns.dir/all' failed.
*** [test/suites/ps/CMakeFiles/tfm_test_suite_ps_ns.dir/all] Error 2.
Makefile:148: recipe for target 'all' failed.